input_size: 14 #17
#input_ids: ['object_pos', 'joints_pos','joints_vel'] #['last_ee_pos', 'joints_pos','joints_vel']
input_ids: ['joints_pos','joints_vel']
n_frames: 4
output_ids: ['command_vel']
hidden_size1: 128
hidden_size2: 128
output_size: 7
lr: 0.001
epochs: 10000
batch_size: 32
load_dir: /home/adriano/Desktop/canopies/code/CanopiesSimulatorROS/workspace/src/imitation_learning/data
save_dir: /home/adriano/Desktop/behavioural_cloning/params #/home/adriano/Desktop/canopies/code/CanopiesSimulatorROS/workspace/src/imitation_learning/src/agent_params
task: grasp2 #push
device: cuda
#