#data
input_size: 7 #14 #17
goal_size: 3
n_frames: 1
output_size: 7 #3

#training
lr: 0.001
epochs: 10000
batch_size: 512
load_dir: data
save_dir: params
checkpoint_dir: save/checkpoints
task: grasping
N_gaussians: 25
weight_decay: 0.0 #0.001
sigma: 0.001